[workspace]
resolver = "2"
members = [ "alere_lib", "cli" , "rust_intervals"]

[workspace.dependencies]
anyhow = "1.0.86"
chrono = { version = "0.4.23", features = ["serde"] }
chrono-tz = "0.6.1"
futures = "0.3"
itertools = "0.13.0"
rust_decimal = "1.35"
